# Generated by Django 5.2 on 2025-04-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreportresult',
            name='average_order_value',
        ),
        migrations.RemoveField(
            model_name='orderreportresult',
            name='total_revenue',
        ),
        migrations.AddField(
            model_name='orderreportresult',
            name='average_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderreportresult',
            name='order_closed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderreportresult',
            name='order_completed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderreportresult',
            name='order_new',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderreportresult',
            name='order_pending',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderreportresult',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
