# Generated by Django 5.2 on 2025-04-25 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_alter_user_role'),
        ('stat_analysis', '0002_remove_orderreportresult_average_order_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreportresult',
            name='service_provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job_report_results', to='registrar.serviceproviderprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobreportresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_report_results', to='stat_analysis.report'),
        ),
        migrations.CreateModel(
            name='UserReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField()),
                ('total_customers', models.IntegerField()),
                ('total_account_managers', models.IntegerField()),
                ('total_service_providers', models.IntegerField()),
                ('average_orders_per_user', models.FloatField()),
                ('average_customers_per_account_manager', models.FloatField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stat_analysis.report')),
            ],
        ),
    ]
