# Generated by Django 5.2 on 2025-04-27 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_analysis', '0003_jobreportresult_service_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='reports_pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
