# Generated by Django 5.2 on 2025-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('account_manager', 'Account Manager'), ('service_provider', 'Service Provider'), ('customer', 'Customer')], default='admin', max_length=20),
        ),
    ]
