# Generated by Django 5.2 on 2025-04-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=10, unique=True)),
                ('job_name', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('regular', 'Regular'), ('wafer_run', 'Wafer Run')], max_length=20)),
                ('starting_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('completion_time', models.FloatField(help_text='Time in days which were spent to complete the job.')),
            ],
        ),
        migrations.CreateModel(
            name='JobState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_statuses', to='execution.job')),
            ],
        ),
    ]
