# Generated by Django 5.2 on 2025-04-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_rename_status_date_jobstate_state_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_states', to='execution.job'),
        ),
    ]
