# Generated by Django 5.2 on 2025-04-25 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_alter_jobstate_job'),
        ('registrar', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='service_provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='registrar.serviceproviderprofile'),
            preserve_default=False,
        ),
    ]
