# Generated by Django 5.2 on 2025-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_job_service_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='starting_date',
        ),
        migrations.AlterField(
            model_name='job',
            name='completion_time',
            field=models.FloatField(blank=True, help_text='Time in days which were spent to complete the job.', null=True),
        ),
    ]
