# Generated by Django 5.2 on 2025-04-26 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_remove_job_end_date_remove_job_starting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstate',
            name='state_date',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
