# Generated by Django 5.2 on 2025-04-26 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_alter_jobstate_state_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstate',
            name='state_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
