# Generated by Django 5.2 on 2025-04-23 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='registrar.accountmanagerprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='registrar.customerprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='registrar.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
        ),
        migrations.AddField(
            model_name='productandservice',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='registrar.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.productandservice'),
        ),
    ]
