# Generated by Django 5.2 on 2025-04-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productandservice',
            name='name',
            field=models.TextField(),
        ),
    ]
