# Generated by Django 5.2 on 2025-04-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_productandservice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_provider',
        ),
    ]
