# Generated by Django 5.2 on 2025-04-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_service_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
