# Generated by Django 5.2 on 2025-04-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
        ('order', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='execution.job'),
        ),
    ]
