# Generated by Django 5.2 on 2025-04-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('closed', 'Closed'), ('completed', 'Completed')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_states', to='order.order')),
            ],
        ),
    ]
